language: node_js
node_js:
  - 12
  - 14
stages:
  - test
jobs:
  include:
    - stage: test
      script: npm run build
      name: "Build"
    - stage: test
      script: npm run lint
      name: "Lint"
    - stage: test
      script: npm run test
      name: "Unit Tests"
      