language: node_js
node_js:
  - 12
  - 14
jobs:
  include:
    - stage: "Tests"
      name: "Unit Tests"
      script: npm run test
    - name: "Lint"
      script: npm run lint
    - name: "Build"
      script: npm run build